import csv

headings = ['Year',
            'Round',
            'Home Team',
            'Away team',
            'Home score',
            'Away score',
            'Home tries',
            'Away tries',
            'Home conversion made',
            'Home conversion attempts',
            'Away conversion made',
            'Away conversion attempts',
            'Home penalties made',
            'Home penatly attempts',
            'Away penalties made',
            'Away penalty attempts',
            'Home 1 point field goals made',
            'Home 1 point field goal attempts',
            'Away 1 point field goals made',
            'Away 1 point field goal attempts',
            'Home 2 point field goals made',
            'Home 2 point field goal attempts',
            'Away 2 point field goals made',
            'Away 2 point field goal attempts',
            'Home Sin bins',
            'Away Sin bins',
            'Home Sent Off',
            'Away Sent Off',
            'Home Half Time Score',
            'Away Half time Score',
            'Home Possession %',
            'Away Possession %',
            'Home Possession time',
            'Away Possession time',
            'Home Completion Rate (%)',
            'Away Copmletion Rate (%)',
            'Home Completions made',
            'Away Completions made',
            'Home All Runs',
            'Away All Runs',
            'Home All Run Metres',
            'Away All Run Metres',
            'Home Post Contact Metres',
            'Away Post Contact Metres',
            'Home Line Breaks',
            'Away Line Breaks',
            'Home Tackle Breaks',
            'Away Tackle Breaks',
            'Home Avg Set Distance',
            'Away Avg Set Distance',
            'Home Kick Return Metres',
            'Away Kick Return Metres',
            #'Home Avg Play the Ball Speed',
            #'Away Avg Play the Ball Speed',
            'Home Offloads',
            'Away Offloads',
            'Home Receipts',
            'Away Receipts',
            'Home Total Passes',
            'Away Total Passes', 
            'Home Dummies',
            'Away Dummies',
            'Home Kicks',
            'Away Kicks',
            'Home Kicking Metres',
            'Away Kicking Metres',
            'Home Forced Dropouts',
            'Away Forced Dropouts',
            'Home Kick Defusal',
            'Away Kick Defusal',
            'Home 40/20',
            'Away 40/20',
            'Home Bombs',
            'Away Bombs', 
            'Home Grubbers',
            'Away Grubbers',
            'Home Effective Tackle %',
            'Away Effective Tackle %',
            'Home Tackles Made',
            'Away Tackles Made',
            'Home Missed Tackles',
            'Away Missed Tackles',
            'Home Intercepts',
            'Away Intercepts',
            'Home Ineffective Tackles',
            'Away Ineffective Tackles',
            'Home Errors', 
            'Away Errors',
            'Home Penalties Conceeded',
            'Away Penalties Conceeded',
            'Home Ruck Infringements',
            'Away Ruck Infringements',
            'Home Inside 10',
            'Away Inside 10',
            'Home On Reports',
            'Away On Reports',
            'Home Interchanges', 
            'Away Interchanges',
            "Home HIA's",
            "Away HIA's"]

def get_team_data(location, game):
    home_indexes = [4,6,8,9,12,13,16,17,20,21,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96]
    away_indexes = []
    for n in range(4, 98):
        if n not in home_indexes:
            away_indexes.append(n)
    indexes = home_indexes if location == 'home' else away_indexes
    team_data = []
    for index in indexes:
        team_data.append(index)
        if location == 'home':
            team_data.append(1)
        else:
            team_data.append(0)
    return team_data

